# Generated by Django 3.1.1 on 2020-09-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='start',
            field=models.TimeField(),
        ),
    ]
