# Generated by Django 3.1.1 on 2020-09-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0002_auto_20200902_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='ffme_license',
        ),
    ]
