# Generated by Django 3.1.1 on 2020-09-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0003_remove_inscription_ffme_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seance_date', models.DateField()),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
    ]
